### ISSUE TITLE
[admin module] sort categories 

### ISSUE THREAD

**Issue by raramuridesign** [pe7er/db8sitedev#19]
Would it be possible to add the option to allow sorting on the admin module

either by
- ordering (preferable)
- alphabetical

Thanks

**Comment by pe7er** [comment]
Good point, thanks @raramuridesign !

**Comment by pe7er** [comment]
Added this functionality in v0.9.3

**Comment by l-arnold** [comment]
I would also say, add it also to the Dashboard.  Not seeing how to do it just now.
