### ISSUE TITLE
Link in About to default checklist not working

### ISSUE THREAD

**Issue by superknutsel** [pe7er/db8sitedev#24]
The link https://github.com/pe7er/db8sitedev/blob/master/db8-site-dev-default-checklist.json is giving a 404 error.

**Comment by pe7er** [comment]
Thanks @superknutsel 
I've changed the link to the default English Checklist on github because I've added a new language. Will be corrected with v0.9.3 that I'll release next week.

**Comment by pe7er** [comment]
Has been corrected in v0.9.3
