### ISSUE TITLE
Typo iExtensions instead of Extensions

### ISSUE THREAD

**Issue by conconnl** [pe7er/db8sitedev#29]
There is a little typo on id 4 "Enable db8 Site Dev Module".
You will see "iExtensions" instead of "Extensions"

<img width="1173" alt="screen shot 2016-07-03 at 01 57 55" src="https://cloud.githubusercontent.com/assets/11913918/16543032/a630473e-40c1-11e6-9e4a-f206e0c7cfff.png">

Regards,
Wilco

**Comment by MATsxm** [comment]
Can be closed as there's a PR #30 
Thanks

**Comment by conconnl** [comment]
Thanks
