### ISSUE TITLE
Typo UNchecked instead of Unchecked

### ISSUE THREAD

**Issue by conconnl** [pe7er/db8sitedev#30]
On the checklist view there is a typo
UNchecked instead Unchecked

<img width="502" alt="screen shot 2016-07-03 at 02 00 38" src="https://cloud.githubusercontent.com/assets/11913918/16543041/1539088c-40c2-11e6-98ca-9eed3244d52b.png">

**Comment by conconnl** [comment]
Found other instances too:
<img width="338" alt="screen shot 2016-07-03 at 02 04 07" src="https://cloud.githubusercontent.com/assets/11913918/16543047/85d9bba4-40c2-11e6-9555-0b1ab4295ea4.png">
<img width="258" alt="screen shot 2016-07-03 at 02 04 14" src="https://cloud.githubusercontent.com/assets/11913918/16543048/88ac8d3e-40c2-11e6-87e5-4024f2647e6a.png">

**Comment by MATsxm** [comment]
Can be closed as we have a PR #37
