### ISSUE TITLE
[Feature] - Checklist Import/Export separate view

### ISSUE THREAD

**Issue by conconnl** [pe7er/db8sitedev#31]
Because you told me I know there is a import feature available.
After a while I found it in the About section, maybe it's better to make a separate view.

<img width="788" alt="screen shot 2016-07-03 at 02 08 37" src="https://cloud.githubusercontent.com/assets/11913918/16543063/4fd1b3c6-40c3-11e6-96a2-9a1251bac711.png">

**Comment by conconnl** [comment]
See #40

**Comment by pe7er** [comment]
Thanks!
