### ISSUE TITLE
Inconsistency with Checklist import function

### ISSUE THREAD

**Issue by conconnl** [pe7er/db8sitedev#33]
When you see the following.
<img width="696" alt="screen shot 2016-07-03 at 02 20 20" src="https://cloud.githubusercontent.com/assets/11913918/16543079/be8d2c68-40c4-11e6-9b91-2ae9a8c674df.png">

You go to options to find the "Enable Import" function.
You will find "Generate Site Checklist Button", with a certain description.
There is no button which states that the Import function is enabled again.

<img width="549" alt="screen shot 2016-07-03 at 02 19 34" src="https://cloud.githubusercontent.com/assets/11913918/16543080/d702b0ce-40c4-11e6-88a6-ede546290b52.png">

**Comment by pe7er** [comment]
Good point. Thanks!

**Comment by pe7er** [comment]
Removed from v 0.9.4
