### ISSUE TITLE
Export / Import of Categories/Check Items

### ISSUE THREAD

**Issue by pe7er** [pe7er/db8sitedev#4]
Replace the hard-coded "Generate Check List" with an export/import functionality

**Comment by raramuridesign** [comment]
+1 This would be great feature.

**Comment by pe7er** [comment]
Currently working on that :-)

**Comment by raramuridesign** [comment]
Great stuff.

**Comment by pe7er** [comment]
@raramuridesign done! 
v0.9.2 has a Checklist Import + Export function
And I've included a default checklist: db8-site-dev-default-checklist.json

**Comment by raramuridesign** [comment]
This is great, thanks.
