### ISSUE TITLE
Uninstall issue

### ISSUE THREAD

**Issue by conconnl** [pe7er/db8sitedev#44]
Hi Peter,

I found an uninstall issue.
You select db8 Site Dev Package and use the uninstall button.
<img width="563" alt="screen shot 2016-07-07 at 23 21 39" src="https://cloud.githubusercontent.com/assets/11913918/16670281/c68f0188-4499-11e6-8796-dce420779407.png">

Then you receive the following error:
As you can see the module is still in the installation.
<img width="689" alt="screen shot 2016-07-07 at 23 21 14" src="https://cloud.githubusercontent.com/assets/11913918/16670299/e357c57a-4499-11e6-9155-14c246a5ca0b.png">

I tested this multiple times on different installations
Regards,
Wilco

**Comment by pe7er** [comment]
Thanks for reporting @conconnl 
I can reproduce the error & have to look for a solution.
